DROP TABLE IF EXISTS LISTING;
DROP TABLE IF EXISTS IMAGE;
DROP TABLE IF EXISTS LISTING_IMAGE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS ROLE;

CREATE SCHEMA LISTING;

CREATE TABLE LISTING (
  Id INT PRIMARY KEY,
  title VARCHAR(25) NOT NULL,
  price DOUBLE NOT NULL,
  description VARCHAR(250) NOT NULL,
  category VARCHAR(20),
  seller_id INT
);

CREATE TABLE USERS (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  password VARCHAR(250) NOT NULL,
  firstName VARCHAR(25) NOT NULL,
  secondName VARCHAR(25) NOT NULL,
  email VARCHAR(30) NOT NULL,
  age INT NOT NULL,
  enabled tinyint(1) NOT NULL,
  listing_id INT
);

ALTER TABLE LISTING ADD CONSTRAINT FK_LISTING_USERS FOREIGN KEY (seller_id) REFERENCES USERS(Id);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_LISTING FOREIGN KEY (listing_id) REFERENCES LISTING(Id);

INSERT INTO USERS (Id, username, password, firstName, secondName, email, age, enabled) VALUES
(1, 'Gesh', '{bcrypt}$2a$04$eFytJDGtjbThXa80FyOOBuFdK2IwjyWefYkMpiBEFlpBwDH.5PM0K', 'Geshev', 'Gecuna', 'Gesh@gesh.ge', 30, 1);

CREATE TABLE ROLE (
Id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(250) NOT NULL
);

INSERT INTO ROLE (name)
VALUES 
('ROLE_USER'),('ROLE_ADMIN');

CREATE TABLE USER_ROLE (
user_id INT NOT NULL,
role_id INT NOT NULL,
UNIQUE KEY user_role_idx_1 (user_id, role_id),
  CONSTRAINT user_role_ibfk_1 FOREIGN KEY (user_id) REFERENCES USERS (Id)
);

INSERT INTO USER_ROLE (user_id, role_id) VALUES
(1, 1);

CREATE TABLE IMAGE (
Id INT PRIMARY KEY NOT NULL,
imageRoute VARCHAR(250)
);

CREATE TABLE LISTING_IMAGE (
listing_Id INT NOT NULL,
image_Id varchar(250) NOT NULL,
UNIQUE KEY listing_image_idx1 (listing_Id, image_Id),
CONSTRAINT listing_image_ibfk1 FOREIGN KEY (listing_Id) REFERENCES LISTING (Id));


CREATE TABLE AUTHORITIES (
username VARCHAR(250) NOT NULL,
authority VARCHAR(250) NOT NULL,
UNIQUE KEY authorities_idx_1 (username, authority),
  CONSTRAINT authorities_ibfk_1 FOREIGN KEY (username) REFERENCES USERS (username)
);

INSERT INTO AUTHORITIES VALUES ('Gesh', 'ROLE_ADMIN');
